// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwOrnd9JCydhQVJpXjOCKmqj1X0Y005sI',
    appId: '1:89445901154:web:d1f5cc693db1352c80023b',
    messagingSenderId: '89445901154',
    projectId: 'jobs-398815',
    authDomain: 'jobs-398815.firebaseapp.com',
    databaseURL: 'https://jobs-398815-default-rtdb.firebaseio.com',
    storageBucket: 'jobs-398815.appspot.com',
    measurementId: 'G-LD1BDNYB3T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_otOm938yoyh-lEg2vU4mEtlsmMbNghg',
    appId: '1:89445901154:android:617c742dec78561c80023b',
    messagingSenderId: '89445901154',
    projectId: 'jobs-398815',
    databaseURL: 'https://jobs-398815-default-rtdb.firebaseio.com',
    storageBucket: 'jobs-398815.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2GuGSQdJldxF9idy3BPnwCw6TNilTdlI',
    appId: '1:89445901154:ios:4d39b55a5d8b3ab080023b',
    messagingSenderId: '89445901154',
    projectId: 'jobs-398815',
    databaseURL: 'https://jobs-398815-default-rtdb.firebaseio.com',
    storageBucket: 'jobs-398815.appspot.com',
    iosClientId: '89445901154-on4o5l9cd70a57vnbgacle2ee2n0991j.apps.googleusercontent.com',
    iosBundleId: 'com.example.jobs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2GuGSQdJldxF9idy3BPnwCw6TNilTdlI',
    appId: '1:89445901154:ios:71272f6fb874551880023b',
    messagingSenderId: '89445901154',
    projectId: 'jobs-398815',
    databaseURL: 'https://jobs-398815-default-rtdb.firebaseio.com',
    storageBucket: 'jobs-398815.appspot.com',
    iosClientId: '89445901154-3kgp8npctq862sf2tdnp6cnk7f4hpno4.apps.googleusercontent.com',
    iosBundleId: 'com.example.jobs.RunnerTests',
  );
}
